// Generated by CoffeeScript 1.7.1
var gutil, map, path;

map = require('map-stream');

gutil = require('gulp-util');

path = require('path');

module.exports = function() {
  return map(function(file, cb) {
    gutil.log(gutil.colors.magenta(path.relative(process.cwd(), file.path)));
    return cb(null, file);
  });
};
