// Generated by CoffeeScript 1.7.1
var colors, log, map, path, print;

map = require('map-stream');

colors = require('colors');

path = require('path');

log = function() {
  var args, sig;
  sig = "[" + (colors.green('gulp')) + "]";
  args = Array.prototype.slice.call(arguments);
  args.unshift(sig);
  return console.log.apply(console, args);
};

print = function(format) {
  if (format == null) {
    format = function(filepath) {
      return filepath;
    };
  }
  return map(function(file, cb) {
    var filepath, formatted;
    filepath = path.relative(process.cwd(), file.path);
    formatted = format(colors.magenta(filepath), filepath);
    if (formatted) {
      print.log(formatted);
    }
    return cb(null, file);
  });
};

print.log = log;

module.exports = print;
